const products = [
  {
    id: 1,
    name: "Wireless Mouse",
    price: 799,
    rating: 4.3,
    category: "Electronics",
    brand: "Logitech",
    inStock: true,
  },
  {
    id: 2,
    name: "Mechanical Keyboard",
    price: 2499,
    rating: 4.7,
    category: "Electronics",
    brand: "Redragon",
    inStock: true,
  },
  {
    id: 3,
    name: "Gaming Headset",
    price: 1899,
    rating: 4.5,
    category: "Electronics",
    brand: "HyperX",
    inStock: false,
  },
  {
    id: 4,
    name: "USB-C Charger",
    price: 999,
    rating: 4.2,
    category: "Accessories",
    brand: "Anker",
    inStock: true,
  },
  {
    id: 5,
    name: "Laptop Stand",
    price: 1299,
    rating: 4.6,
    category: "Accessories",
    brand: "Portronics",
    inStock: true,
  },
  {
    id: 6,
    name: "Bluetooth Speaker",
    price: 3499,
    rating: 4.4,
    category: "Audio",
    brand: "JBL",
    inStock: true,
  },
  {
    id: 7,
    name: "Smart Watch",
    price: 5999,
    rating: 4.5,
    category: "Wearables",
    brand: "Noise",
    inStock: false,
  },
  {
    id: 8,
    name: "Fitness Band",
    price: 2499,
    rating: 4.1,
    category: "Wearables",
    brand: "Xiaomi",
    inStock: true,
  },
  {
    id: 9,
    name: "Noise Cancelling Earbuds",
    price: 4499,
    rating: 4.6,
    category: "Audio",
    brand: "Realme",
    inStock: true,
  },
  {
    id: 10,
    name: "Portable SSD",
    price: 6999,
    rating: 4.8,
    category: "Storage",
    brand: "Samsung",
    inStock: true,
  },

  {
    id: 11,
    name: "External Hard Drive",
    price: 5499,
    rating: 4.4,
    category: "Storage",
    brand: "Seagate",
    inStock: false,
  },
  {
    id: 12,
    name: "Webcam",
    price: 2999,
    rating: 4.3,
    category: "Electronics",
    brand: "Logitech",
    inStock: true,
  },
  {
    id: 13,
    name: "LED Monitor",
    price: 12499,
    rating: 4.7,
    category: "Electronics",
    brand: "LG",
    inStock: true,
  },
  {
    id: 14,
    name: "Gaming Chair",
    price: 8999,
    rating: 4.5,
    category: "Furniture",
    brand: "Green Soul",
    inStock: true,
  },
  {
    id: 15,
    name: "Office Desk",
    price: 7499,
    rating: 4.2,
    category: "Furniture",
    brand: "IKEA",
    inStock: false,
  },
  {
    id: 16,
    name: "Desk Lamp",
    price: 899,
    rating: 4.4,
    category: "Home",
    brand: "Philips",
    inStock: true,
  },
  {
    id: 17,
    name: "Wireless Charger",
    price: 1499,
    rating: 4.3,
    category: "Accessories",
    brand: "Spigen",
    inStock: true,
  },
  {
    id: 18,
    name: "Power Bank",
    price: 1999,
    rating: 4.5,
    category: "Accessories",
    brand: "Mi",
    inStock: true,
  },
  {
    id: 19,
    name: "HDMI Cable",
    price: 499,
    rating: 4.1,
    category: "Accessories",
    brand: "AmazonBasics",
    inStock: true,
  },
  {
    id: 20,
    name: "USB Hub",
    price: 1199,
    rating: 4.4,
    category: "Accessories",
    brand: "Ugreen",
    inStock: false,
  },

  {
    id: 21,
    name: "Graphics Tablet",
    price: 4999,
    rating: 4.6,
    category: "Electronics",
    brand: "XP-Pen",
    inStock: true,
  },
  {
    id: 22,
    name: "Drawing Pen",
    price: 1299,
    rating: 4.3,
    category: "Electronics",
    brand: "Wacom",
    inStock: true,
  },
  {
    id: 23,
    name: "Smartphone Case",
    price: 399,
    rating: 4.2,
    category: "Accessories",
    brand: "Spigen",
    inStock: true,
  },
  {
    id: 24,
    name: "Screen Protector",
    price: 299,
    rating: 4.0,
    category: "Accessories",
    brand: "CaseU",
    inStock: true,
  },
  {
    id: 25,
    name: "Phone Tripod",
    price: 799,
    rating: 4.3,
    category: "Photography",
    brand: "Digitek",
    inStock: false,
  },
  {
    id: 26,
    name: "Action Camera",
    price: 18999,
    rating: 4.6,
    category: "Photography",
    brand: "GoPro",
    inStock: true,
  },
  {
    id: 27,
    name: "DSLR Camera",
    price: 48999,
    rating: 4.8,
    category: "Photography",
    brand: "Canon",
    inStock: true,
  },
  {
    id: 28,
    name: "Camera Lens",
    price: 24999,
    rating: 4.7,
    category: "Photography",
    brand: "Nikon",
    inStock: false,
  },
  {
    id: 29,
    name: "Camera Bag",
    price: 1599,
    rating: 4.5,
    category: "Photography",
    brand: "Wildcraft",
    inStock: true,
  },
  {
    id: 30,
    name: "Memory Card",
    price: 999,
    rating: 4.6,
    category: "Storage",
    brand: "SanDisk",
    inStock: true,
  },

  {
    id: 31,
    name: "Microphone",
    price: 3999,
    rating: 4.5,
    category: "Audio",
    brand: "Blue",
    inStock: true,
  },
  {
    id: 32,
    name: "Ring Light",
    price: 1499,
    rating: 4.3,
    category: "Photography",
    brand: "Digitek",
    inStock: true,
  },
  {
    id: 33,
    name: "Podcast Mixer",
    price: 9999,
    rating: 4.7,
    category: "Audio",
    brand: "Rode",
    inStock: false,
  },
  {
    id: 34,
    name: "Smart TV",
    price: 35999,
    rating: 4.6,
    category: "Electronics",
    brand: "Sony",
    inStock: true,
  },
  {
    id: 35,
    name: "Streaming Device",
    price: 3999,
    rating: 4.4,
    category: "Entertainment",
    brand: "Amazon",
    inStock: true,
  },
  {
    id: 36,
    name: "Home Theater",
    price: 18999,
    rating: 4.5,
    category: "Audio",
    brand: "Sony",
    inStock: true,
  },
  {
    id: 37,
    name: "Router",
    price: 2499,
    rating: 4.3,
    category: "Networking",
    brand: "TP-Link",
    inStock: true,
  },
  {
    id: 38,
    name: "WiFi Extender",
    price: 1999,
    rating: 4.2,
    category: "Networking",
    brand: "Netgear",
    inStock: false,
  },
  {
    id: 39,
    name: "Network Switch",
    price: 3299,
    rating: 4.4,
    category: "Networking",
    brand: "Cisco",
    inStock: true,
  },
  {
    id: 40,
    name: "Printer",
    price: 8499,
    rating: 4.5,
    category: "Office",
    brand: "HP",
    inStock: true,
  },

  // Continue the same pattern...

  {
    id: 41,
    name: "Scanner",
    price: 5999,
    rating: 4.3,
    category: "Office",
    brand: "Canon",
    inStock: true,
  },
  {
    id: 42,
    name: "Ink Cartridge",
    price: 1299,
    rating: 4.2,
    category: "Office",
    brand: "HP",
    inStock: false,
  },
  {
    id: 43,
    name: "Notebook",
    price: 199,
    rating: 4.7,
    category: "Stationery",
    brand: "Classmate",
    inStock: true,
  },
  {
    id: 44,
    name: "Ball Pen",
    price: 50,
    rating: 4.4,
    category: "Stationery",
    brand: "Cello",
    inStock: true,
  },
  {
    id: 45,
    name: "Marker Set",
    price: 299,
    rating: 4.3,
    category: "Stationery",
    brand: "Camlin",
    inStock: true,
  },
  {
    id: 46,
    name: "Backpack",
    price: 1899,
    rating: 4.6,
    category: "Bags",
    brand: "Skybags",
    inStock: true,
  },
  {
    id: 47,
    name: "Travel Bag",
    price: 2999,
    rating: 4.5,
    category: "Bags",
    brand: "American Tourister",
    inStock: false,
  },
  {
    id: 48,
    name: "Water Bottle",
    price: 399,
    rating: 4.4,
    category: "Kitchen",
    brand: "Milton",
    inStock: true,
  },
  {
    id: 49,
    name: "Coffee Mug",
    price: 299,
    rating: 4.5,
    category: "Kitchen",
    brand: "Borosil",
    inStock: true,
  },
  {
    id: 50,
    name: "Lunch Box",
    price: 699,
    rating: 4.2,
    category: "Kitchen",
    brand: "Milton",
    inStock: true,
  },

  {
    id: 51,
    name: "Electric Kettle",
    price: 1499,
    rating: 4.5,
    category: "Appliances",
    brand: "Prestige",
    inStock: true,
  },
  {
    id: 52,
    name: "Air Fryer",
    price: 4999,
    rating: 4.6,
    category: "Appliances",
    brand: "Philips",
    inStock: true,
  },
  {
    id: 53,
    name: "Blender",
    price: 2499,
    rating: 4.3,
    category: "Appliances",
    brand: "NutriBullet",
    inStock: false,
  },
  {
    id: 54,
    name: "Mixer Grinder",
    price: 3499,
    rating: 4.4,
    category: "Appliances",
    brand: "Bajaj",
    inStock: true,
  },
  {
    id: 55,
    name: "Rice Cooker",
    price: 2799,
    rating: 4.5,
    category: "Appliances",
    brand: "Prestige",
    inStock: true,
  },
  {
    id: 56,
    name: "Microwave Oven",
    price: 7999,
    rating: 4.6,
    category: "Appliances",
    brand: "Samsung",
    inStock: true,
  },
  {
    id: 57,
    name: "Vacuum Cleaner",
    price: 6499,
    rating: 4.4,
    category: "Home",
    brand: "Eureka Forbes",
    inStock: false,
  },
  {
    id: 58,
    name: "Steam Iron",
    price: 1899,
    rating: 4.3,
    category: "Home",
    brand: "Philips",
    inStock: true,
  },
  {
    id: 59,
    name: "Ceiling Fan",
    price: 2499,
    rating: 4.5,
    category: "Home",
    brand: "Havells",
    inStock: true,
  },
  {
    id: 60,
    name: "Table Fan",
    price: 1799,
    rating: 4.2,
    category: "Home",
    brand: "Usha",
    inStock: true,
  },

  {
    id: 61,
    name: "Air Purifier",
    price: 8999,
    rating: 4.6,
    category: "Home",
    brand: "Mi",
    inStock: true,
  },
  {
    id: 62,
    name: "Humidifier",
    price: 1999,
    rating: 4.3,
    category: "Home",
    brand: "Philips",
    inStock: false,
  },
  {
    id: 63,
    name: "Electric Toothbrush",
    price: 2499,
    rating: 4.4,
    category: "Personal Care",
    brand: "Oral-B",
    inStock: true,
  },
  {
    id: 64,
    name: "Hair Dryer",
    price: 1799,
    rating: 4.5,
    category: "Personal Care",
    brand: "Philips",
    inStock: true,
  },
  {
    id: 65,
    name: "Hair Straightener",
    price: 2299,
    rating: 4.4,
    category: "Personal Care",
    brand: "Havells",
    inStock: true,
  },
  {
    id: 66,
    name: "Beard Trimmer",
    price: 1499,
    rating: 4.6,
    category: "Personal Care",
    brand: "Philips",
    inStock: true,
  },
  {
    id: 67,
    name: "Electric Shaver",
    price: 3299,
    rating: 4.3,
    category: "Personal Care",
    brand: "Braun",
    inStock: false,
  },
  {
    id: 68,
    name: "Yoga Mat",
    price: 799,
    rating: 4.7,
    category: "Fitness",
    brand: "Boldfit",
    inStock: true,
  },
  {
    id: 69,
    name: "Dumbbell Set",
    price: 3499,
    rating: 4.6,
    category: "Fitness",
    brand: "Kore",
    inStock: true,
  },
  {
    id: 70,
    name: "Resistance Bands",
    price: 699,
    rating: 4.4,
    category: "Fitness",
    brand: "Boldfit",
    inStock: true,
  },

  {
    id: 71,
    name: "Skipping Rope",
    price: 299,
    rating: 4.3,
    category: "Fitness",
    brand: "Strauss",
    inStock: true,
  },
  {
    id: 72,
    name: "Treadmill",
    price: 34999,
    rating: 4.6,
    category: "Fitness",
    brand: "PowerMax",
    inStock: false,
  },
  {
    id: 73,
    name: "Exercise Bike",
    price: 15999,
    rating: 4.5,
    category: "Fitness",
    brand: "Lifeline",
    inStock: true,
  },
  {
    id: 74,
    name: "Football",
    price: 899,
    rating: 4.4,
    category: "Sports",
    brand: "Nivia",
    inStock: true,
  },
  {
    id: 75,
    name: "Basketball",
    price: 999,
    rating: 4.5,
    category: "Sports",
    brand: "Spalding",
    inStock: true,
  },
  {
    id: 76,
    name: "Cricket Bat",
    price: 2499,
    rating: 4.6,
    category: "Sports",
    brand: "SG",
    inStock: true,
  },
  {
    id: 77,
    name: "Cricket Ball",
    price: 399,
    rating: 4.3,
    category: "Sports",
    brand: "SG",
    inStock: true,
  },
  {
    id: 78,
    name: "Badminton Racket",
    price: 1999,
    rating: 4.5,
    category: "Sports",
    brand: "Yonex",
    inStock: false,
  },
  {
    id: 79,
    name: "Tennis Racket",
    price: 3499,
    rating: 4.6,
    category: "Sports",
    brand: "Wilson",
    inStock: true,
  },
  {
    id: 80,
    name: "Table Tennis Paddle",
    price: 1499,
    rating: 4.4,
    category: "Sports",
    brand: "Stiga",
    inStock: true,
  },

  {
    id: 81,
    name: "Running Shoes",
    price: 3999,
    rating: 4.7,
    category: "Footwear",
    brand: "Nike",
    inStock: true,
  },
  {
    id: 82,
    name: "Casual Sneakers",
    price: 2999,
    rating: 4.5,
    category: "Footwear",
    brand: "Puma",
    inStock: true,
  },
  {
    id: 83,
    name: "Leather Wallet",
    price: 999,
    rating: 4.4,
    category: "Fashion",
    brand: "WildHorn",
    inStock: false,
  },
  {
    id: 84,
    name: "Sunglasses",
    price: 1499,
    rating: 4.5,
    category: "Fashion",
    brand: "Ray-Ban",
    inStock: true,
  },
  {
    id: 85,
    name: "Wrist Watch",
    price: 5999,
    rating: 4.6,
    category: "Fashion",
    brand: "Casio",
    inStock: true,
  },
  {
    id: 86,
    name: "Leather Belt",
    price: 799,
    rating: 4.3,
    category: "Fashion",
    brand: "Levi's",
    inStock: true,
  },
  {
    id: 87,
    name: "Winter Jacket",
    price: 3499,
    rating: 4.5,
    category: "Clothing",
    brand: "Woodland",
    inStock: true,
  },
  {
    id: 88,
    name: "Hoodie",
    price: 1499,
    rating: 4.4,
    category: "Clothing",
    brand: "H&M",
    inStock: true,
  },
  {
    id: 89,
    name: "Cotton T-Shirt",
    price: 699,
    rating: 4.3,
    category: "Clothing",
    brand: "Uniqlo",
    inStock: false,
  },
  {
    id: 90,
    name: "Denim Jeans",
    price: 1999,
    rating: 4.5,
    category: "Clothing",
    brand: "Levi's",
    inStock: true,
  },

  {
    id: 91,
    name: "Formal Shirt",
    price: 1499,
    rating: 4.4,
    category: "Clothing",
    brand: "Van Heusen",
    inStock: true,
  },
  {
    id: 92,
    name: "Track Pants",
    price: 999,
    rating: 4.3,
    category: "Clothing",
    brand: "Adidas",
    inStock: true,
  },
  {
    id: 93,
    name: "Bluetooth Adapter",
    price: 599,
    rating: 4.2,
    category: "Accessories",
    brand: "TP-Link",
    inStock: true,
  },
  {
    id: 94,
    name: "Flash Drive",
    price: 799,
    rating: 4.6,
    category: "Storage",
    brand: "SanDisk",
    inStock: true,
  },
  {
    id: 95,
    name: "Portable Projector",
    price: 14999,
    rating: 4.5,
    category: "Electronics",
    brand: "Epson",
    inStock: false,
  },
  {
    id: 96,
    name: "Smart Door Lock",
    price: 10999,
    rating: 4.6,
    category: "Home Security",
    brand: "Godrej",
    inStock: true,
  },
  {
    id: 97,
    name: "Security Camera",
    price: 3499,
    rating: 4.5,
    category: "Home Security",
    brand: "CP Plus",
    inStock: true,
  },
  {
    id: 98,
    name: "Drone",
    price: 45999,
    rating: 4.7,
    category: "Photography",
    brand: "DJI",
    inStock: false,
  },
  {
    id: 99,
    name: "VR Headset",
    price: 29999,
    rating: 4.8,
    category: "Gaming",
    brand: "Meta",
    inStock: true,
  },
  {
    id: 100,
    name: "E-Reader",
    price: 9999,
    rating: 4.6,
    category: "Electronics",
    brand: "Amazon",
    inStock: true,
  },
];


export default products;